export const UTC5='[UTC-5]';
export const UTC5_VAL="UTC-5";
export const UTC0='[UTC-0]';
export const UTC0_VAL="UTC-0";
export const AM="AM";
export const PM="PM";
export const PREVIOUS_WEEK="Previous week";
export const NEXT_WEEK="Next week";
export const PAST="Past";